---
include:
  # Central (left) — Studio RPC over USB
  - board: xiao_ble/nrf52840/zmk
    shield: jisaku_1_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: jisaku_1_left

  # Peripheral (right)
  - board: xiao_ble/nrf52840/zmk
    shield: jisaku_1_right rgbled_adapter
    artifact-name: jisaku_1_right

  # BLE pairing reset
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset
