# DYA Studio (Peripheral)
CONFIG_ZMK_BATTERY_HISTORY=y
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
# フラッシュ書き込み頻度を左と統一(省電力・フラッシュ寿命)
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=60000

# RGB LEDステータス表示
CONFIG_RGBLED_WIDGET=y
