manifest:
  remotes:
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: bakajaan
      url-base: https://github.com/bakajaan
  projects:
    - name: zmk
      remote: cormoran
      revision: v0.3-branch+dya
      import: app/west.yml
    - name: zmk-module-ble-management
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-module-battery-history
      remote: cormoran
      revision: main
    - name: zmk-module-settings-rpc
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3-branch
    # 共通キーマップ定義(jisaku_1 / aerogu34で共有)
    - name: zmk-keymap-common
      remote: bakajaan
      revision: main
  self:
    path: config
